name : matrix
on : [push]

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        node_version : [4,6,8]

      include: 
        os: [macos-latest]
        node_version: 6
        is_macos_6: "true"

      exclude:
        os: ubuntu-latest
        node_version: 4 
    runs-on : ${{ matrix.os }}
    env:
      IS_MACOS_6: ${{matrix.is_macos_6}}
    steps:
      - name : Node version
        run :  node -v

      - uses:  actions/setup-node@v1
        with:  
          node-version: ${{matrix.node_version}}
      - name : Node version 2
        run : |
          node -v
          echo $IS_MACOS_6
        
        