name : matrix
on : [push]

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        node_version : [4,6,8]
    runs-on : ${{ matrix.os }}
    steps:
      - name : Node version
        run :  node -v
      - uses:  actions/setup-node@v1
        with:  
          node-version: ${{matrix.node_version}}
      - name : Node version 2
        run :  node -v
        